# Generated by Django 5.1.2 on 2024-10-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bank',
            name='loan_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bank',
            name='transaction_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
