# Generated by Django 5.1.2 on 2024-10-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bank_interest_rate_bank_loan_fee_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='loan_fee_percentage',
        ),
    ]
